#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 31 11:30:00 2018

@author: sterling
"""
import pandas as pd
import time

df = pd.read_excel('BRH.xls') # Reads the Excel File and creates a dataframe 
# Column Headers
df = df[['street#', 'street', 'city', 'state', 'zip','hoa','mStreet#','mStreet','mCity','mState','mZip','account','first','last','home','work','cell','email', 'Address Type']]

df['mStreet'] = df['street']
df['mState'] = df['state']
df['mZip'] = df['zip']
df['mCity'] = df['city']

next_address_attributes = df[['Address Type', 'street', 'city', 'state', 'zip']].shift(-1)

# Create a series to indicate whether information should be drawn from next row
# All the decision-making is right here
get_attributes_from_next_address = ((df['Address Type'] == 'Property Address')
    & (next_address_attributes['Address Type'] != 'Property Address'))

df.loc[get_attributes_from_next_address, 'mStreet'] = next_address_attributes.loc[get_attributes_from_next_address, 'street']
df.loc[get_attributes_from_next_address, 'mCity'] = next_address_attributes.loc[get_attributes_from_next_address, 'city']
df.loc[get_attributes_from_next_address, 'mState'] = next_address_attributes.loc[get_attributes_from_next_address, 'state']
df.loc[get_attributes_from_next_address, 'mZip'] = next_address_attributes.loc[get_attributes_from_next_address, 'zip']

df.to_excel('BRHOut3.xls')
print('operation complete in:', time.process_time(), 'ms')